"use strict";

const fs=require("fs");
const path=require("path");
const templates=require("./projectTemplates");

class FileGenerator{

create(type,target){

if(!templates[type]){

return false;

}

fs.mkdirSync(target,{recursive:true});

for(const file of templates[type].files){

const p=path.join(target,file);

if(!fs.existsSync(p)){

fs.writeFileSync(
p,
"// Generated by Jarvis Builder\n"
);

}

}

return true;

}

}

module.exports=new FileGenerator();
