'use strict';

module.exports = {

  express() {

    return {

      "index.js":
`const express = require('express');
const app = express();

app.use(express.json());

app.get("/", (req,res)=>{
    res.send("Jarvis API");
});

app.listen(3000,()=>{
    console.log("Server started");
});
`,

      "README.md":
`# Express API

Generated by Jarvis V7
`,

      "routes/api.js":
`const router=require("express").Router();

router.get("/ping",(req,res)=>{
    res.json({message:"pong"});
});

module.exports=router;
`,

      "controllers/apiController.js":
`exports.ping=(req,res)=>{
    res.json({message:"pong"});
};
`,

      "config/db.js":
`module.exports={};
`

    };

  }

};
